#!/usr/bin/env Rscript
# Monte Carlo Simulation Template for PMM Research Papers
# Author: Generated by PMM-Research Skill
# Purpose: Compare PMM2 vs OLS/MLE for parameter estimation

library(EstemPMM)
library(parallel)

#' Run Monte Carlo Simulation for PMM2 Performance
#'
#' @param n_sim Number of simulation replications (default: 2000)
#' @param sample_sizes Vector of sample sizes to test (default: c(50, 100, 200, 500))
#' @param distributions List of error distributions to test
#' @param true_beta True regression coefficient (default: 0.5)
#' @param seed Random seed for reproducibility (default: 12345)
#' @param n_cores Number of cores for parallel processing (default: 4)
#' @return Data frame with simulation results
run_pmm_monte_carlo <- function(n_sim = 2000,
                                 sample_sizes = c(50, 100, 200, 500),
                                 distributions = list(
                                   gamma = function(n) rgamma(n, shape = 2, scale = 1) - 2,
                                   exp = function(n) rexp(n, rate = 1) - 1,
                                   lognormal = function(n) rlnorm(n, 0, 0.5) - exp(0.125)
                                 ),
                                 true_beta = 0.5,
                                 seed = 12345,
                                 n_cores = 4) {

  set.seed(seed)

  # Initialize results storage
  results_list <- list()

  # Loop over sample sizes and distributions
  for (n in sample_sizes) {
    for (dist_name in names(distributions)) {

      cat(sprintf("\nRunning: n=%d, distribution=%s\n", n, dist_name))

      # Parallel simulation
      sim_results <- mclapply(1:n_sim, function(i) {

        # Generate data
        x <- rnorm(n)
        errors <- distributions[[dist_name]](n)
        y <- 1 + true_beta * x + errors
        data <- data.frame(x = x, y = y)

        # Fit models
        ols <- lm(y ~ x, data = data)

        pmm2_fit <- tryCatch({
          lm_pmm2(y ~ x, data = data)
        }, error = function(e) {
          return(NULL)
        })

        # Extract results
        if (!is.null(pmm2_fit)) {
          return(data.frame(
            n = n,
            distribution = dist_name,
            replication = i,
            ols_beta = coef(ols)[2],
            pmm2_beta = coef(pmm2_fit)[2],
            ols_se = sqrt(vcov(ols)[2, 2]),
            pmm2_se = sqrt(vcov(pmm2_fit)[2, 2]),
            ols_bias = coef(ols)[2] - true_beta,
            pmm2_bias = coef(pmm2_fit)[2] - true_beta
          ))
        } else {
          return(NULL)
        }

      }, mc.cores = n_cores)

      # Combine results
      sim_df <- do.call(rbind, sim_results[!sapply(sim_results, is.null)])
      results_list[[paste0("n", n, "_", dist_name)]] <- sim_df
    }
  }

  # Combine all results
  all_results <- do.call(rbind, results_list)

  return(all_results)
}

#' Summarize Monte Carlo Results
#'
#' @param results Data frame from run_pmm_monte_carlo()
#' @return Summary statistics data frame
summarize_mc_results <- function(results) {

  library(dplyr)

  summary_stats <- results %>%
    group_by(n, distribution) %>%
    summarise(
      # Bias
      ols_mean_bias = mean(ols_bias, na.rm = TRUE),
      pmm2_mean_bias = mean(pmm2_bias, na.rm = TRUE),

      # Variance
      ols_variance = var(ols_beta, na.rm = TRUE),
      pmm2_variance = var(pmm2_beta, na.rm = TRUE),

      # MSE
      ols_mse = mean(ols_bias^2, na.rm = TRUE),
      pmm2_mse = mean(pmm2_bias^2, na.rm = TRUE),

      # Relative efficiency
      relative_efficiency = ols_variance / pmm2_variance,
      efficiency_gain_pct = (1 - pmm2_variance / ols_variance) * 100,

      # Standard errors
      ols_mean_se = mean(ols_se, na.rm = TRUE),
      pmm2_mean_se = mean(pmm2_se, na.rm = TRUE),

      .groups = "drop"
    )

  return(summary_stats)
}

#' Create LaTeX Table from Results
#'
#' @param summary_stats Summary data frame
#' @param output_file Path to output .tex file
create_latex_table <- function(summary_stats, output_file = "results/mc_comparison.tex") {

  library(xtable)

  # Format for publication
  table_df <- summary_stats %>%
    select(n, distribution,
           ols_mean_bias, pmm2_mean_bias,
           ols_variance, pmm2_variance,
           efficiency_gain_pct)

  # Create LaTeX table
  xtab <- xtable(table_df,
                 digits = c(0, 0, 0, 4, 4, 6, 6, 2),
                 caption = "Monte Carlo Comparison: OLS vs PMM2",
                 label = "tab:mc_results")

  print(xtab,
        file = output_file,
        include.rownames = FALSE,
        booktabs = TRUE)

  cat(sprintf("LaTeX table saved to: %s\n", output_file))
}

# ============================================
# MAIN EXECUTION
# ============================================

if (!interactive()) {

  cat("==============================================\n")
  cat("Monte Carlo Simulation: PMM2 vs OLS\n")
  cat("==============================================\n\n")

  # Run simulation
  results <- run_pmm_monte_carlo(
    n_sim = 2000,
    sample_sizes = c(50, 100, 200, 500),
    seed = 12345,
    n_cores = 4
  )

  # Save raw results
  dir.create("results", showWarnings = FALSE)
  saveRDS(results, "results/monte_carlo_raw.rds")
  write.csv(results, "results/monte_carlo_raw.csv", row.names = FALSE)
  cat("\n✓ Raw results saved to results/monte_carlo_raw.csv\n")

  # Summarize
  summary_stats <- summarize_mc_results(results)
  write.csv(summary_stats, "results/monte_carlo_summary.csv", row.names = FALSE)
  cat("✓ Summary statistics saved to results/monte_carlo_summary.csv\n")

  # Create LaTeX table
  create_latex_table(summary_stats)
  cat("✓ LaTeX table saved to results/mc_comparison.tex\n")

  # Print summary
  cat("\n==============================================\n")
  cat("SUMMARY STATISTICS\n")
  cat("==============================================\n\n")
  print(summary_stats, n = Inf)

  cat("\n==============================================\n")
  cat("✓ Monte Carlo simulation complete!\n")
  cat("==============================================\n")
}
