#!/usr/bin/env Rscript
# Complete Paper Analysis Template for PMM Research
# Author: Generated by PMM-Research Skill
# Purpose: Full reproducibility package for academic paper

library(EstemPMM)
library(ggplot2)
library(gridExtra)

#' Full Paper Analysis Pipeline
#' Includes: data loading, model fitting, diagnostics, visualization
main_analysis <- function() {

  cat("==============================================\n")
  cat("PMM Research Paper - Full Analysis Pipeline\n")
  cat("==============================================\n\n")

  # Create output directories
  dir.create("results", showWarnings = FALSE)
  dir.create("results/plots", showWarnings = FALSE)
  dir.create("results/tables", showWarnings = FALSE)

  # ==========================================
  # STEP 1: DATA PREPARATION
  # ==========================================
  cat("STEP 1: Loading and preparing data...\n")

  # Example: WTI Crude Oil Prices (replace with your data)
  if (require(EstemPMM, quietly = TRUE)) {
    data(DCOILWTICO)
    y_raw <- DCOILWTICO$value
  } else {
    # Generate synthetic data as fallback
    set.seed(42)
    n <- 200
    y_raw <- arima.sim(list(ar = 0.7), n = n) + rgamma(n, shape = 2) - 2
  }

  # Take first differences for stationarity
  y <- diff(y_raw)

  # Descriptive statistics
  desc_stats <- data.frame(
    Statistic = c("Mean", "SD", "Skewness", "Kurtosis", "Min", "Max", "N"),
    Value = c(
      mean(y, na.rm = TRUE),
      sd(y, na.rm = TRUE),
      moments::skewness(y),
      moments::kurtosis(y) - 3,  # Excess kurtosis
      min(y, na.rm = TRUE),
      max(y, na.rm = TRUE),
      length(y)
    )
  )

  write.csv(desc_stats, "results/tables/descriptive_stats.csv", row.names = FALSE)
  cat("✓ Descriptive statistics saved\n")

  # ==========================================
  # STEP 2: MODEL ESTIMATION
  # ==========================================
  cat("\nSTEP 2: Fitting ARIMA models (OLS vs PMM2)...\n")

  # Test different ARIMA specifications
  orders <- list(
    c(1, 0, 0),  # AR(1)
    c(2, 0, 0),  # AR(2)
    c(1, 0, 1),  # ARMA(1,1)
    c(2, 0, 1)   # ARMA(2,1)
  )

  results_list <- list()

  for (order in orders) {
    p <- order[1]; d <- order[2]; q <- order[3]
    model_name <- sprintf("ARIMA(%d,%d,%d)", p, d, q)

    cat(sprintf("  Fitting %s...\n", model_name))

    # CSS-ML estimation
    fit_cssml <- tryCatch({
      arima(y, order = order, method = "CSS-ML")
    }, error = function(e) NULL)

    # PMM2 estimation
    fit_pmm2 <- tryCatch({
      if (q == 0) {
        ar_pmm2(y, order = p)
      } else {
        arma_pmm2(y, order = c(p, q))
      }
    }, error = function(e) NULL)

    # Store results
    if (!is.null(fit_cssml) && !is.null(fit_pmm2)) {
      results_list[[model_name]] <- list(
        model = model_name,
        cssml_aic = AIC(fit_cssml),
        cssml_bic = BIC(fit_cssml),
        pmm2_aic = AIC(fit_pmm2),
        pmm2_bic = BIC(fit_pmm2),
        cssml_loglik = logLik(fit_cssml)[1],
        pmm2_loglik = logLik(fit_pmm2)[1],
        cssml_fit = fit_cssml,
        pmm2_fit = fit_pmm2
      )
    }
  }

  # Create comparison table
  comparison_df <- do.call(rbind, lapply(results_list, function(x) {
    data.frame(
      Model = x$model,
      CSS_ML_AIC = x$cssml_aic,
      PMM2_AIC = x$pmm2_aic,
      CSS_ML_BIC = x$cssml_bic,
      PMM2_BIC = x$pmm2_bic,
      Delta_AIC = x$pmm2_aic - x$cssml_aic,
      Delta_BIC = x$pmm2_bic - x$cssml_bic
    )
  }))

  write.csv(comparison_df, "results/tables/model_comparison.csv", row.names = FALSE)
  cat("✓ Model comparison table saved\n")

  # ==========================================
  # STEP 3: DIAGNOSTIC TESTS
  # ==========================================
  cat("\nSTEP 3: Running diagnostic tests...\n")

  # Select best model (lowest AIC)
  best_model_name <- comparison_df$Model[which.min(comparison_df$PMM2_AIC)]
  best_fits <- results_list[[best_model_name]]

  # Residual diagnostics for PMM2
  resid_pmm2 <- residuals(best_fits$pmm2_fit)

  diagnostics <- data.frame(
    Test = c("Ljung-Box (lag 10)", "Jarque-Bera", "ARCH (lag 5)"),
    Statistic = c(
      Box.test(resid_pmm2, lag = 10, type = "Ljung-Box")$statistic,
      moments::jarque.test(resid_pmm2)$statistic,
      FinTS::ArchTest(resid_pmm2, lags = 5)$statistic
    ),
    P_value = c(
      Box.test(resid_pmm2, lag = 10, type = "Ljung-Box")$p.value,
      moments::jarque.test(resid_pmm2)$p.value,
      FinTS::ArchTest(resid_pmm2, lags = 5)$p.value
    )
  )

  write.csv(diagnostics, "results/tables/diagnostics.csv", row.names = FALSE)
  cat("✓ Diagnostic tests saved\n")

  # ==========================================
  # STEP 4: CREATE VISUALIZATIONS
  # ==========================================
  cat("\nSTEP 4: Creating publication-quality plots...\n")

  # Plot 1: Time series
  p1 <- ggplot(data.frame(t = 1:length(y), y = y), aes(x = t, y = y)) +
    geom_line(color = "steelblue") +
    labs(title = "First Differenced Series", x = "Time", y = "Value") +
    theme_minimal()

  ggsave("results/plots/01_time_series.png", p1, width = 8, height = 4, dpi = 300)

  # Plot 2: AIC Comparison
  p2 <- ggplot(comparison_df, aes(x = Model)) +
    geom_point(aes(y = CSS_ML_AIC, color = "CSS-ML"), size = 3) +
    geom_point(aes(y = PMM2_AIC, color = "PMM2"), size = 3) +
    labs(title = "AIC Comparison", y = "AIC", color = "Method") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  ggsave("results/plots/02_aic_comparison.png", p2, width = 8, height = 5, dpi = 300)

  # Plot 3: Residual QQ-plot
  p3 <- ggplot(data.frame(resid = resid_pmm2), aes(sample = resid)) +
    stat_qq() +
    stat_qq_line(color = "red") +
    labs(title = sprintf("QQ-Plot: %s (PMM2)", best_model_name)) +
    theme_minimal()

  ggsave("results/plots/03_qq_plot.png", p3, width = 6, height = 6, dpi = 300)

  # Plot 4: ACF of residuals
  png("results/plots/04_acf_residuals.png", width = 800, height = 500, res = 100)
  acf(resid_pmm2, main = sprintf("ACF of Residuals: %s (PMM2)", best_model_name))
  dev.off()

  cat("✓ All plots saved to results/plots/\n")

  # ==========================================
  # STEP 5: GENERATE MARKDOWN REPORT
  # ==========================================
  cat("\nSTEP 5: Generating narrative report...\n")

  report_md <- sprintf("
# PMM Research Paper - Analysis Report

## Data Summary

%s

- **Skewness**: %.3f
- **Excess Kurtosis**: %.3f
- **Observations**: %d

## Model Comparison

Best model by AIC: **%s**

%s

## Diagnostic Tests

%s

## Figures

1. Time Series: `plots/01_time_series.png`
2. AIC Comparison: `plots/02_aic_comparison.png`
3. QQ-Plot: `plots/03_qq_plot.png`
4. ACF of Residuals: `plots/04_acf_residuals.png`

## Conclusion

The PMM2 method %s compared to CSS-ML for this dataset.

",
    paste(capture.output(print(desc_stats)), collapse = "\n"),
    desc_stats$Value[desc_stats$Statistic == "Skewness"],
    desc_stats$Value[desc_stats$Statistic == "Kurtosis"],
    desc_stats$Value[desc_stats$Statistic == "N"],
    best_model_name,
    paste(capture.output(print(comparison_df)), collapse = "\n"),
    paste(capture.output(print(diagnostics)), collapse = "\n"),
    ifelse(best_fits$pmm2_aic < best_fits$cssml_aic,
           "provided improvement in model fit",
           "showed similar performance")
  )

  writeLines(report_md, "results/ANALYSIS_REPORT.md")
  cat("✓ Report saved to results/ANALYSIS_REPORT.md\n")

  # ==========================================
  # SUMMARY
  # ==========================================
  cat("\n==============================================\n")
  cat("✓ ANALYSIS COMPLETE\n")
  cat("==============================================\n")
  cat(sprintf("\nBest Model: %s\n", best_model_name))
  cat(sprintf("PMM2 AIC: %.2f | CSS-ML AIC: %.2f | Δ = %.2f\n",
              best_fits$pmm2_aic, best_fits$cssml_aic,
              best_fits$pmm2_aic - best_fits$cssml_aic))
  cat("\nOutput files:\n")
  cat("  - results/tables/        (CSV tables)\n")
  cat("  - results/plots/         (PNG figures)\n")
  cat("  - results/ANALYSIS_REPORT.md\n")
  cat("\n==============================================\n")

  return(list(
    comparison = comparison_df,
    diagnostics = diagnostics,
    best_model = best_model_name
  ))
}

# ============================================
# RUN ANALYSIS
# ============================================

if (!interactive()) {
  results <- main_analysis()
}
