#!/usr/bin/env Rscript
# scripts/07_generate_paper_tables.R
# Generate LaTeX tables for the paper from CSV results.
#
# Usage: Rscript scripts/07_generate_paper_tables.R
# Or from R: source("scripts/07_generate_paper_tables.R")

suppressPackageStartupMessages({
  library(knitr)
  library(dplyr)
})

# ── Paths ────────────────────────────────────────────────────────────────────
proj_root  <- here::here()
tables_in  <- file.path(proj_root, "results", "tables")
tables_out <- file.path(proj_root, "paper", "tables")
dir.create(tables_out, showWarnings = FALSE, recursive = TRUE)

cat("Reading from:", tables_in, "\n")
cat("Writing to: ", tables_out, "\n\n")

# ── Helper: write LaTeX table ─────────────────────────────────────────────────
write_tex <- function(df, filename, caption, label, digits = 3, ...) {
  path <- file.path(tables_out, filename)
  tex  <- knitr::kable(
    df,
    format   = "latex",
    booktabs = TRUE,
    digits   = digits,
    caption  = caption,
    label    = label,
    ...
  )
  writeLines(c("% Auto-generated by scripts/07_generate_paper_tables.R",
               "% Do not edit manually — rerun the script instead.",
               tex),
             path)
  cat("  Written:", filename, "\n")
  invisible(path)
}

# ── Table 1: Theoretical TN characteristics ──────────────────────────────────
cat("=== Table 1: Theoretical TN characteristics ===\n")

t1 <- read.csv(file.path(tables_in, "T1_theoretical.csv")) |>
  select(lambda, gamma4, g3, improvement_pct, is_bimodal) |>
  mutate(
    gamma4         = round(gamma4, 4),
    g3             = round(g3, 4),
    improvement_pct = sprintf("%.1f%%", improvement_pct),
    is_bimodal     = ifelse(is_bimodal, "Yes", "No")
  ) |>
  rename(
    "$\\lambda$"    = lambda,
    "$\\gamma_4$"   = gamma4,
    "$g_3$ theor."  = g3,
    "Reduction"     = improvement_pct,
    "Bimodal?"      = is_bimodal
  )

write_tex(
  t1,
  filename = "T1_theoretical.tex",
  caption  = paste0(
    "Theoretical characteristics of the TN distribution and PMM3 efficiency. ",
    "$\\lambda$ -- shape parameter; $\\gamma_4$ -- excess kurtosis; ",
    "$g_3$ -- variance ratio PMM3/OLS; Reduction -- improvement over OLS."
  ),
  label    = "tab:T1",
  digits   = 4,
  escape   = FALSE
)

# ── Table 2: Monte Carlo results (n = 100 and n = 200) ───────────────────────
cat("\n=== Table 2: Monte Carlo results ===\n")

t2_raw <- read.csv(file.path(tables_in, "T2_monte_carlo.csv"))

# Pivot wide: one row per (lambda, n), columns for MLE-TN and PMM3
t1_theor <- read.csv(file.path(tables_in, "T1_theoretical.csv")) |>
  select(lambda, gamma4, g3) |>
  rename(g3_theor = g3)

t2 <- t2_raw |>
  filter(n %in% c(100, 200), method %in% c("MLE", "PMM3")) |>
  mutate(method = recode(method, "MLE" = "MLE-TN")) |>
  select(lambda, n, method, are, g3_empirical) |>
  tidyr::pivot_wider(
    names_from  = method,
    values_from = c(are, g3_empirical),
    names_glue  = "{.value}_{method}"
  ) |>
  merge(t1_theor, by = "lambda") |>
  mutate(
    across(starts_with("are_"), \(x) round(x, 3)),
    across(starts_with("g3_emp"), \(x) round(x, 3)),
    g3_theor = round(g3_theor, 3),
    delta_pct = round((g3_empirical_PMM3 - g3_theor) / g3_theor * 100, 1)
  ) |>
  arrange(lambda, n) |>
  select(lambda, gamma4, n, `are_MLE-TN`, are_PMM3,
         g3_empirical_PMM3, g3_theor, delta_pct) |>
  rename(
    "$\\lambda$"         = lambda,
    "$\\gamma_4$"        = gamma4,
    "$n$"                = n,
    "ARE(MLE-TN)"        = `are_MLE-TN`,
    "ARE(PMM3)"          = are_PMM3,
    "$g_3^{\\rm emp}$"   = g3_empirical_PMM3,
    "$g_3^{\\rm theor}$" = g3_theor,
    "$\\Delta g_3$, \\%" = delta_pct
  )

write_tex(
  t2,
  filename = "T2_monte_carlo.tex",
  caption  = paste0(
    "Monte Carlo results ($M = 500$, $n \\in \\{100, 200\\}$). ",
    "ARE $= \\widehat{\\mathrm{Var}}(\\text{OLS})",
    " / \\widehat{\\mathrm{Var}}(\\text{method})$;",
    " values $> 1$ indicate improvement over OLS."
  ),
  label   = "tab:T2",
  digits  = 4,
  escape  = FALSE
)

# ── Table 3: Misspecification robustness ─────────────────────────────────────
cat("\n=== Table 3: Misspecification robustness ===\n")

t6 <- read.csv(file.path(tables_in, "T6_misspecification.csv")) |>
  mutate(
    distribution = tools::toTitleCase(as.character(distribution)),
    are_mle      = round(are_mle, 3),
    are_pmm3     = round(are_pmm3, 3),
    bias_mle     = round(bias_mle, 4),
    bias_pmm3    = round(bias_pmm3, 4)
  ) |>
  select(distribution, are_mle, are_pmm3, bias_mle, bias_pmm3) |>
  rename(
    "True DGP"       = distribution,
    "ARE(MLE-TN)"    = are_mle,
    "ARE(PMM3)"      = are_pmm3,
    "Bias(MLE-TN)"   = bias_mle,
    "Bias(PMM3)"     = bias_pmm3
  )

write_tex(
  t6,
  filename = "T3_misspecification.tex",
  caption  = paste0(
    "Robustness to misspecification ($n = 100$, $M = 500$). ",
    "DGP is not TN; MLE-TN assumes TN. ",
    "ARE $= \\widehat{\\mathrm{Var}}(\\text{OLS})",
    " / \\widehat{\\mathrm{Var}}(\\text{method})$."
  ),
  label  = "tab:T3",
  digits = 4,
  escape = FALSE
)

# ── Table 4: Real data — Iris versicolor ─────────────────────────────────────
cat("\n=== Table 4: Iris versicolor real data ===\n")

iris_res <- read.csv(file.path(tables_in, "iris_versicolor_results.csv")) |>
  mutate(
    method  = recode(method, "MLE-TN" = "MLE-TN"),
    beta1   = round(beta1, 4),
    loo_mse = round(loo_mse, 4),
    g3_emp  = round(g3_emp, 3)
  ) |>
  rename(
    "Method"                 = method,
    "$\\hat{\\beta}_1$"      = beta1,
    "LOO-MSE"                = loo_mse,
    "$g_3^{\\rm emp}$"       = g3_emp
  )

write_tex(
  iris_res,
  filename = "T4_iris_versicolor.tex",
  caption  = paste0(
    "Estimation results for Iris versicolor ($n = 50$, ",
    "Sepal.Length $\\sim$ Sepal.Width, $\\hat{\\gamma}_4 = -0.966$). ",
    "$g_3^{\\rm emp} = \\widehat{\\mathrm{Var}}(\\text{method})",
    " / \\widehat{\\mathrm{Var}}(\\text{OLS})$,",
    " $B = 2000$ bootstrap replications."
  ),
  label  = "tab:T4",
  digits = 4,
  escape = FALSE
)

# ── Table 5: Bimodal convergence ─────────────────────────────────────────────
cat("\n=== Table 5: Bimodal convergence ===\n")

t7 <- read.csv(file.path(tables_in, "T7_bimodal_test.csv")) |>
  mutate(
    is_bimodal  = ifelse(is_bimodal, "Yes", "No"),
    bias_pmm3   = round(bias_pmm3, 4),
    conv_rate   = sprintf("%.0f%%", conv_rate * 100),
    na_pct      = sprintf("%.0f%%", na_pct)
  ) |>
  select(lambda, is_bimodal, bias_pmm3, conv_rate, na_pct) |>
  rename(
    "$\\lambda$"   = lambda,
    "Bimodal?"     = is_bimodal,
    "Bias(PMM3)"   = bias_pmm3,
    "Conv. rate"   = conv_rate,
    "NA\\%"        = na_pct
  )

write_tex(
  t7,
  filename = "T5_bimodal_convergence.tex",
  caption  = paste0(
    "PMM3 Newton--Raphson convergence for bimodal TN distributions ",
    "($n = 100$, $M = 500$). All cases converge at 100\\%."
  ),
  label  = "tab:T5",
  digits = 4,
  escape = FALSE
)

# ── Summary ───────────────────────────────────────────────────────────────────
cat("\n=== Done ===\n")
n_tex <- length(list.files(tables_out, "*.tex"))
cat("Generated", n_tex, "LaTeX tables in", tables_out, "\n")
